### ISSUE TITLE
Come on dude

### ISSUE THREAD

**Issue by tekulvw** [JonnyBoy2000/BrooklynCogs#1]
You've totally ripped my cogs with zero credit and you didn't even bother to fork my repo. Seriously?

**Comment by Real-Wizard** [comment]
well just in Jonny's Defence This Cogs are the Cogs Loaded up in Brooklyn, so they are made specificly for brooklyn

**Comment by tekulvw** [comment]
Yeah yeah, I didn't realize who the owner of this repo was, it's all good.

**Comment by Real-Wizard** [comment]
o lol
